;
; File generated by cc65 v 2.11.0
;
	.fopt		compiler,"cc65 v 2.11.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.import		_printf
	.import		_text
	.export		_main

.segment	"RODATA"

L0001:
	.byte	$25,$73,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	lda     #<(_text)
	ldx     #>(_text)
	jsr     pushax
	ldy     #$04
	jsr     _printf
	ldx     #$00
	lda     #$00
	jmp     L0002
L0002:	rts

.endproc

